"""add server uptime checks

Revision ID: 0cac12d1d101
Revises: d1f3a7b2c5e8
Create Date: 2026-06-02 23:14:23.547315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0cac12d1d101'
down_revision: Union[str, None] = 'd1f3a7b2c5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_uptime_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_uptime_checks_checked_at'), 'server_uptime_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_server_uptime_checks_server_id'), 'server_uptime_checks', ['server_id'], unique=False)
    op.alter_column('servers', 'share_code',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'share_code',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_index(op.f('ix_server_uptime_checks_server_id'), table_name='server_uptime_checks')
    op.drop_index(op.f('ix_server_uptime_checks_checked_at'), table_name='server_uptime_checks')
    op.drop_table('server_uptime_checks')
    # ### end Alembic commands ###
