"""add_management_enabled_to_servers

Revision ID: 53cbe68d39d2
Revises: ffdc72bc6f60
Create Date: 2026-06-03 14:18:50.726487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53cbe68d39d2'
down_revision: Union[str, None] = 'ffdc72bc6f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('management_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'management_enabled')
    # ### end Alembic commands ###
