"""add source_share_code to modpacks

Revision ID: 7f317934956d
Revises: b1a2d1539a10
Create Date: 2026-04-27 15:54:04.683302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f317934956d'
down_revision: Union[str, None] = 'b1a2d1539a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modpacks', sa.Column('source_share_code', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modpacks', 'source_share_code')
    # ### end Alembic commands ###
