"""add modpack changelog

Revision ID: 7f5f4fa459f7
Revises: e7a3d91f4c82
Create Date: 2026-05-05 00:57:15.283885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f5f4fa459f7'
down_revision: Union[str, None] = 'e7a3d91f4c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modpack_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modpack_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('added', 'removed', name='changelogaction'), nullable=False),
    sa.Column('mod_name', sa.String(length=255), nullable=False),
    sa.Column('mod_icon_url', sa.String(length=500), nullable=True),
    sa.Column('modrinth_project_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modpack_id'], ['modpacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modpack_changelog')
    # ### end Alembic commands ###
