"""initial schema

Revision ID: b1a2d1539a10
Revises: 
Create Date: 2026-04-26 20:31:45.715039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b1a2d1539a10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('modpacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('game_version', sa.String(length=20), nullable=False),
    sa.Column('loader', sa.String(length=50), nullable=False),
    sa.Column('share_code', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modpacks_share_code'), 'modpacks', ['share_code'], unique=True)
    op.create_table('server_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('server_ip', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('game_version', sa.String(length=20), nullable=False),
    sa.Column('loader', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modpack_mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modpack_id', sa.Integer(), nullable=False),
    sa.Column('modrinth_project_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('side', sa.Enum('client', 'server', 'both', name='modside'), nullable=False),
    sa.ForeignKeyConstraint(['modpack_id'], ['modpacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_profile_id', sa.Integer(), nullable=False),
    sa.Column('modrinth_project_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('side', sa.Enum('client', 'server', 'both', name='modside'), nullable=False),
    sa.ForeignKeyConstraint(['server_profile_id'], ['server_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_mods')
    op.drop_table('modpack_mods')
    op.drop_table('server_profiles')
    op.drop_index(op.f('ix_modpacks_share_code'), table_name='modpacks')
    op.drop_table('modpacks')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
