"""add description to modpacks

Revision ID: b4aa0df0bd10
Revises: c00502526fc2
Create Date: 2026-05-06 01:23:46.841438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4aa0df0bd10'
down_revision: Union[str, None] = 'c00502526fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modpacks', sa.Column('description', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modpacks', 'description')
    # ### end Alembic commands ###
