"""add version_number to modpack_changelog

Revision ID: c00502526fc2
Revises: 7f5f4fa459f7
Create Date: 2026-05-05 01:08:11.829691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c00502526fc2'
down_revision: Union[str, None] = '7f5f4fa459f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modpack_changelog', sa.Column('version_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modpack_changelog', 'version_number')
    # ### end Alembic commands ###
