"""add icon_url to servers

Revision ID: ffdc72bc6f60
Revises: 0cac12d1d101
Create Date: 2026-06-03 00:33:22.262073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ffdc72bc6f60'
down_revision: Union[str, None] = '0cac12d1d101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('icon_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'icon_url')
    # ### end Alembic commands ###
